<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<Version>1.0.1</Version>
		<Authors>jukefr</Authors>
		<OutputType>Library</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<EnableDefaultCompileItems>false</EnableDefaultCompileItems>
	</PropertyGroup>

	<PropertyGroup Condition="'$(ResonitePath)' == ''">
		<!-- default windows and linux paths, manual fallback if both don't turn up anything -->
		<ResonitePath Condition="'$(OS)' == 'Windows_NT' and Exists('C:\Program Files (x86)\Steam\steamapps\common\Resonite')">C:/Program Files (x86)/Steam/steamapps/common/Resonite</ResonitePath>

		<ResonitePath Condition="'$(OS)' != 'Windows_NT' and Exists('$(HOME)/.steam/steam/steamapps/common/Resonite')">$(HOME)/.steam/steam/steamapps/common/Resonite</ResonitePath>

		<ResonitePath Condition="'$(ResonitePath)' == ''">G:\SteamLibrary\steamapps\common\Resonite</ResonitePath>
	</PropertyGroup>

	<!-- path containing managed dlls. for post-split, this is the same as resonite path, but still here just in case -->
	<PropertyGroup>
		<ManagedPath>$(ResonitePath)</ManagedPath>
	</PropertyGroup>

	<ItemGroup>
		<ResoniteReference Include="Elements.Assets"/>
		<ResoniteReference Include="Renderite.Host"/>

		<Reference Include="ResoniteModLoader">
			<HintPath>$(ResonitePath)/Libraries/ResoniteModLoader.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="HarmonyLib">
			<HintPath>$(ResonitePath)/rml_libs/0Harmony.dll</HintPath>
			<Private>false</Private>
		</Reference>
	</ItemGroup>

	<ItemGroup>
		<Reference Include="@(ResoniteReference)">
			<Name>%(ResoniteReference.Identity)</Name>
			<HintPath Condition="'%(HintPath)' == '' And Exists('$(ManagedPath)/%(Identity).dll')">$(ManagedPath)/%(Identity).dll</HintPath>
			<HintPath Condition="'%(HintPath)' == '' And Exists('$(ManagedPath)/%(Identity).exe')">$(ManagedPath)/%(Identity).exe</HintPath>
			<Private>false</Private>
		</Reference>
	</ItemGroup>

	<ItemGroup Condition="'$(Configuration)' == 'Debug' and Exists('$(ResonitePath)/rml_libs/ResoniteHotReloadLib.dll')">
		<Reference Include="ResoniteHotReloadLib">
			<HintPath>$(ResonitePath)/rml_libs/ResoniteHotReloadLib.dll</HintPath>
		</Reference>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="LinuxClipboard.Core/LinuxClipboard.Core.csproj" Private="false" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Costura.Fody" Version="6.0.0" PrivateAssets="All" />
	</ItemGroup>

	<ItemGroup>
		<Compile Include="LinuxClipboard.cs" />
	</ItemGroup>

	<Target Name="Copy" DependsOnTargets="Build">
		<Message Text="Copying $(TargetFileName) to $(ResonitePath)/rml_mods" Importance="High" />
		<Copy SourceFiles="$(TargetPath)" DestinationFolder="$(ResonitePath)/rml_mods" />
		<Message Condition="'$(Configuration)' == 'Debug'" Text="Debug build, copying $(TargetFileName) to $(ResonitePath)/rml_mods/HotReloadMods" Importance="High" />
		<Copy Condition="'$(Configuration)' == 'Debug'" SourceFiles="$(TargetPath)" DestinationFolder="$(ResonitePath)/rml_mods/HotReloadMods" />
		<Delete Condition="'$(Configuration)' == 'Release'" Files="$(ResonitePath)/rml_mods/HotReloadMods/$(AssemblyName).dll" />
	</Target>

</Project>
