<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Library</OutputType>
    <AssemblyName>Elements.Assets</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Renderite.Host">
      <HintPath>../prebuilt/Renderite.Host.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
